### ISSUE TITLE
Python conflict

### ISSUE THREAD

**Issue by sdhuerta** [OSUrobotics/palantir#3]
Invalid systax error on print statement when running roscore.

Traceback (most recent call last):
  File "/nfs/attic/smartw/users/huertas/catkin_ws/devel/bin/roscore", line 5, in <module>
    exec(fh.read())
  File "<string>", line 62, in <module>
  File "/nfs/attic/smartw/users/huertas/catkin_ws/devel/lib/python2.7/dist-packages/roslaunch/**init**.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 225
    print palantir_file_name
                           ^
SyntaxError: invalid syntax

**Comment by MatthewRueben** [comment]
Sounds like a problem from further up in the file, like an unclosed parenthesis or incorrect tabbing or something.
